sudo: required
dist: trusty
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
before_script:
  - pip install -r requirements.txt
script:
  - sbt clean test
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
