sudo: required
dist: trusty
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
before_script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - pip install -r requirements.txt
script:
  - sbt clean test
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
